### ISSUE TITLE
Can not load new file

### ISSUE THREAD

**Issue by ultravires** [ONLYOFFICE/document-editor-vue#10]
I changed `config` props. But the document can not be changed.

Changed: 
```js
// example
{
  url: '',
  callback: ''
}
```

The document title have been changed, But content is old.

**Comment by aleksandrfedorov97** [comment]
Hi [ultravires](https://github.com/ultravires), you also have to change the document key https://github.com/ONLYOFFICE/document-editor-vue/blob/master/src/model/config.ts#L25

**Comment by aleksandrfedorov97** [comment]
[ultravires](https://github.com/ultravires), what version of ONLYOFFICE editors are you using?

**Comment by ultravires** [comment]
@aleksandrfedorov97 7.2.1-34

**Comment by aleksandrfedorov97** [comment]
[ultravires](https://github.com/ultravires), I can't figure out what could be the reason. I created a test project with a document refresh button. You can deploy it and make sure that the content of the document is successfully updated.
[test-project.zip](https://github.com/ONLYOFFICE/document-editor-vue/files/10390629/test-project.zip)

**Comment by ultravires** [comment]
@aleksandrfedorov97  OK，My code is the same as yours。I'm trying to find other reasons, if I found, I will write it here. Thanks!

**Comment by ultravires** [comment]
I refreshed the whole page. Make sure the websocket URL changes.
