### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by wwjje** [ONLYOFFICE/document-editor-vue#16]
import { DocumentEditor } from "@onlyoffice/document-editor-vue";  引入就报错
![图片](https://user-images.githubusercontent.com/39489205/229426514-c1cebd60-d0c2-4ded-aa2a-88db64c426b3.png)

**Comment by aleksandrfedorov97** [comment]
Hi [wwjje](https://github.com/wwjje), can you provide more information please. What set of components are you using the component with? It would be great if you gave an example where this error is reproduced.

**Comment by wwjje** [comment]
我只是引入了document-editor-vue，就报错了。我决定使用原生js实现了

**Comment by aleksandrfedorov97** [comment]
[wwjje](https://github.com/wwjje), can you provide an example project where the problem occurs?

**Comment by wwjje** [comment]
https://github.com/PanJiaChen/vue-admin-template  我用的这个基础模板，然后引入document-editor-vue依赖，在页面中import { DocumentEditor } from "@onlyoffice/document-editor-vue";引入就报错了

**Comment by aleksandrfedorov97** [comment]
[wwjje](https://github.com/wwjje), your project template uses vue version 2 (https://github.com/PanJiaChen/vue-admin-template/blob/master/package.json#L24), but our component requires vue version 3 (https://github.com/ONLYOFFICE/document-editor-vue/blob/master/package.json#L30). Therefore, when you ran command "npm install" , you should have received this error: 
![image](https://user-images.githubusercontent.com/62958171/230291574-38a3e9cf-e665-4806-8cdc-1da5f7d54d0a.png)
