### ISSUE TITLE
I opened the editor, but kept loading demos

### ISSUE THREAD

**Issue by huyipu** [ONLYOFFICE/document-editor-vue#18]
I opened the editor, but kept loading demos
<img width="394" alt="22222" src="https://github.com/ONLYOFFICE/document-editor-vue/assets/71433928/2a5135dd-d89d-4c9e-be89-c90ef299fc55">

**Comment by SergeyKorneyev** [comment]
Hello,
Could you check if the Document Server itself is functioning? The easiest way to do it is to access `your-document-server-address/healthcheck` in a browser. If the result is "false", there are issues with the installation.
