### ISSUE TITLE
how should i use the history event

### ISSUE THREAD

**Issue by zhannb** [ONLYOFFICE/document-editor-vue#24]
there are no method with name refreshHistory and setHistoryData in the vueEditor, but Official document say must use refreshHistory  before onRequestHistory and setHistoryData  before onRequestHistoryData

**Comment by LinneyS** [comment]
Hi !
You can use `events_onRequestHistory`
See it in [readme](https://github.com/ONLYOFFICE/document-editor-vue/blob/master/README.md)
