### ISSUE TITLE
is there a version for vue 2?

### ISSUE THREAD

**Issue by wellenzhong** [ONLYOFFICE/document-editor-vue#4]
Hello dear:
I tried this package in my  old project,which is built with **vue2**.it Throwed an error, I found that this package is **vue3 only**, so,**i'd like to ask for a version of vue2**,is there any help?or how can I get more information for it?thanks.

**Comment by SergeyKorneyev** [comment]
Hello,
I'm afraid there are currently no plans to make components for older versions of Vue.
